BTC:
  init_action: 'BUY'
  init_price: 870000
  #desire_price: 820000
  yield: 2
  # If you sell coin, it will be sold 1%('more_price') more expesive than 'mid-price'
  # If you buy coin, it will be bought 1%('more_price') cheaper  than 'mid-price'
  more_price: 1

