source 'https://rubygems.org'

gem 'bitflyer', :git => 'git@github.com:begaborn/bitflyer.git', branch: 'master'
gem 'zaif', :git => 'git@github.com:begaborn/zaif-ruby.git', branch: 'master'
gem 'korbit', :git => 'git@github.com:begaborn/korbit.git', branch: 'master'
gem 'ruby_coincheck_client', :git => 'git@github.com:17number/ruby_coincheck_client.git', branch: 'master'
gem 'activesupport'
gem 'aws-sdk'
gem 'color_echo'
gem 'pry-byebug'
